language: node_js
node_js:
  - 14.13.1

notifications:
  email: false

branches:
  only:
    - main

before_install:
  - chmod +x .travis/build-condition.sh
  - chmod +x .travis/build.sh

install: skip

matrix:
  include:
    - env: TARGET=projects/csd PROJECT=csd
    - env: TARGET=projects/librarian PROJECT=librarian

script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "$TARGET is being built" && .travis/build.sh $PROJECT; else echo "$TARGET is NOT being built"; fi
